name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Swift
      uses: fwal/setup-swift@v1.5.0
    - name: Run tests
      run: swift test --enable-code-coverage --enable-test-discovery -Xswiftc -warnings-as-errors
    - name: Generate test coverage report
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: maxep/spm-lcov-action@0.3.1
      with:
        output-file: ./coverage/lcov.info
    - name: Post test coverage report
      if: ${{ matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request' }}
      uses: romeovs/lcov-reporter-action@v0.2.17
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
    - name: Enforce test coverage threshhold
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: ChicagoFlutter/lcov-cop@v1.0.2
      with:
        path: ./coverage/lcov.info
        min_coverage: 0
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run SwiftLint --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
